# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0096_auto_20180803_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencedWoopayObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=190, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SessionWoopayObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=190, unique=True)),
            ],
        ),
    ]
