# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woopay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedwoopayobject',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
