# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woopay', '0002_referencedwoopayobject_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedwoopayobject',
            name='key',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
